name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker image
      run:  | 
        BUILD_ID=$(date +%s)
        SECONDARY_TAG=latest
        IMAGE_REPO=mattb912/python-flask-hello-world


        docker build . --file Dockerfile --tag $IMAGE_REPO:$BUILD_ID --tag $IMAGE_REPO:$SECONDARY_TAG


        echo "${{ secrets.DOCKERHUB_SECRET }}" | docker login --username "${{ secrets.DOCKERHUB_USER }}" --password-stdin 
    
        docker push $IMAGE_REPO:$BUILD_ID
        docker push $IMAGE_REPO:$SECONDARY_TAG