name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag mattb912/python-flask-hello-world:$(date +%s) --tag mattb912/python-flask-hello-world:latest
        docker push mattb912/python-flask-hello-world:$(date +%s)
        docker push mattb912/python-flask-hello-world:latest