name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  | 
        BUILD_ID=$(date +%s)
        SECONDARY_TAG=latest
        docker build . --file Dockerfile --tag mattb912/python-flask-hello-world:$BUILD_ID --tag mattb912/python-flask-hello-world:$SECONDARY_TAG

    - name: Login and push image
      run: |
        IMAGE_REPO=mattb912/python-flask-hello-world
        docker login --username "${{ secrets.DOCKERHUB_USER }}" --password "${{ secrets.DOCKERHUB_SECRET }}"
    
        docker push $IMAGE_REPO:$BUILD_ID
        docker push $IMAGE_REPO:SECONDARY_TAG