name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mattb912/python-flask-hello-world:$(date +%s) --tag mattb912/python-flask-hello-world:latest

    - name: Login and push image
      run: |
        IMAGE_REPO=mattb912/python-flask-hello-world
        docker login --username "${{ secrets.DOCKERHUB_USER }}" --password "${{ secrets.DOCKERHUB_SECRET }}"
    
        docker push $IMAGE_REPO:$(date +%s)
        docker push $IMAGE_REPO:latest